#ifndef RR_LOG_CONSTS_H
#define RR_LOG_CONSTS_H

#define RR_ENTRY_TYPE_INVALID 0
#define RR_ENTRY_TYPE_INTR 0x1
#define RR_ENTRY_TYPE_IN   0x2
#define RR_ENTRY_TYPE_MS   0x3
#define RR_ENTRY_TYPE_MMIO_IN   0x4
#define RR_ENTRY_TYPE_RDTSC   0x5
#define RR_ENTRY_TYPE_RDPMC   0x6
#define RR_ENTRY_TYPE_OUT   0x7
#define RR_ENTRY_TYPE_CHECK 0x8
#define RR_ENTRY_TYPE_KBD 0x9
#define RR_ENTRY_TYPE_NET 0xa
#define RR_ENTRY_TYPE_HPET 0xb
#define RR_ENTRY_TYPE_SPK 0xc
#define RR_ENTRY_TYPE_MEM 0xd
#define RR_ENTRY_TYPE_CMOS 0xe
#define RR_ENTRY_TYPE_HYP 0xf
#define RR_ENTRY_TYPE_EOMR 0x10    /* end of micro replay */
#define RR_ENTRY_TYPE_SER 0x11
#define RR_ENTRY_TYPE_PIT 0x12
#define RR_ENTRY_TYPE_APIC 0x13
#define RR_ENTRY_TYPE_PM 0x14
#define RR_ENTRY_TYPE_DBG 0x15
#define RR_ENTRY_TYPE_MICROREPLAY_DUMP 0x16
#define RR_ENTRY_TYPE_SHUTDOWN 0x17
#define RR_ENTRY_TYPE_STRING 0x18
#define RR_ENTRY_TYPE_DISK_WRITE 0x19
#define RR_ENTRY_TYPE_SHM_NETWORK 0x20
#define RR_ENTRY_TYPE_BARRIER 0x21
#define RR_ENTRY_TYPE_DISK_READ 0x22
#define RR_ENTRY_TYPE_STRING_BEGIN 0x23
#define RR_ENTRY_TYPE_NETWORK_SEND 0x24
//#define RR_ENTRY_TYPE_CPU_NUMBER 0x25
 #define RR_ENTRY_TYPE_CPU_SWITCH 0x25
#define RR_ENTRY_TYPE_PIC 0x26
#define RR_ENTRY_TYPE_BMDMA_STATUS 0x27
#endif
